;this file for FamiTone2 library generated by text2data tool
.export _music_data

_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export _music_data
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ; 00 : Instrument 1
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $80, $32, $a5, $32, $a5, $36, $a5, $36, $a5, $3a, $a5, $3a, $a5, $3c, $a5, $3c, $a5, $00, $a5, $3c, $a5, $00, $a5, $3c
	.byte $a5, $00, $a5, $32, $a5, $32, $a5, $36, $a5, $36, $a5, $32, $a5, $32, $a5, $36, $a5, $36, $a5, $00, $f5
@song0ref49:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb
	.byte $ff, $0c
	.word @song0ref49
	.byte $ff, $0c
	.word @song0ref49
	.byte $f9, $f9, $cb, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $0c
	.word @song0ref49
	.byte $ff, $0c
	.word @song0ref49
	.byte $ff, $0c
	.word @song0ref49
	.byte $ff, $0c
	.word @song0ref49
	.byte $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $ff, $0c
	.word @song0ref49
	.byte $ff, $0c
	.word @song0ref49
	.byte $ff, $0c
	.word @song0ref49
	.byte $ff, $0c
	.word @song0ref49
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $0c
	.word @song0ref49
	.byte $ff, $0c
	.word @song0ref49
	.byte $ff, $0c
	.word @song0ref49
	.byte $ff, $0c
	.word @song0ref49
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $0c
	.word @song0ref49
	.byte $ff, $0c
	.word @song0ref49
	.byte $ff, $0c
	.word @song0ref49
	.byte $ff, $0c
	.word @song0ref49
	.byte $fd
	.word @song0ch4loop
